CREATE TABLE [dbo].[Configuration]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[Key] varchar(50) NOT NULL,
	[Value] varchar(50) NULL
)
go
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20180321-194513] ON [dbo].[Configuration]
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

